using Generator.Database.Analyzers;
using Generator.Database.Models;
using System.Text;

namespace Generator.Database.Generators
{
    public class JoinEntityGenerator(string rootNamespace = "")
    {
        private readonly string RootNamespace = rootNamespace;

        private const string CstJoinEntityTemplate = @"// <auto-generated />
// This file was automatically generated from SQL procedure join definition. Do not edit manually.

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace {NAMESPACE};

/// <summary>
/// {DESCRIPTION}
/// </summary>
public class {CLASS_NAME}
{
{PROPERTIES}
}";

        public List<GeneratedFile> GenerateJoinEntities(string database, List<ProcedureSchema> procedures, List<TableSchema> tables)
        {
            var generatedFiles = new List<GeneratedFile>();

            // 테이블명 → TableSchema 빠른 조회용 딕셔너리
            var tableMap = tables.ToDictionary(t => t.TableName, t => t, StringComparer.OrdinalIgnoreCase);

            foreach (var procedure in procedures)
            {
                if (string.IsNullOrEmpty(procedure.EntityName) ||
                    !string.Equals(procedure.SourceType, "join", StringComparison.OrdinalIgnoreCase) ||
                    procedure.JoinSources.Count == 0)
                {
                    continue;
                }

                var generatedFile = GenerateJoinEntity(database, procedure, tableMap);
                if (generatedFile != null)
                {
                    generatedFiles.Add(generatedFile);
                }
            }

            return generatedFiles;
        }

        private GeneratedFile? GenerateJoinEntity(
            string database,
            ProcedureSchema procedure,
            Dictionary<string, TableSchema> tableMap)
        {
            var entityName = procedure.EntityName!;
            var builder = new StringBuilder();

            foreach (var joinSource in procedure.JoinSources)
            {
                if (!tableMap.TryGetValue(joinSource.TableName, out var tableSchema))
                {
                    Console.WriteLine($"Warning: Table '{joinSource.TableName}' not found in schema. Skipping join source for {entityName}.");
                    continue;
                }

                // 컬럼명 → ColumnSchema 딕셔너리
                var columnMap = tableSchema.Columns.ToDictionary(c => c.ColumnName, c => c, StringComparer.OrdinalIgnoreCase);

                foreach (var columnName in joinSource.Columns)
                {
                    if (!columnMap.TryGetValue(columnName, out var column))
                    {
                        Console.WriteLine($"Warning: Column '{columnName}' not found in table '{joinSource.TableName}'. Skipping.");
                        continue;
                    }

                    builder.AppendLine(GenerateProperty(column));
                }
            }

            var propertiesText = builder.ToString().TrimEnd();
            if (string.IsNullOrEmpty(propertiesText))
            {
                return null;
            }

            var code = CstJoinEntityTemplate
                .Replace("{NAMESPACE}", NamespaceBuilder.Build(RootNamespace, database, "Entities"))
                .Replace("{DESCRIPTION}", $"{entityName} (JOIN: {string.Join(" + ", procedure.JoinSources.Select(j => j.TableName))})")
                .Replace("{CLASS_NAME}", entityName)
                .Replace("{PROPERTIES}", propertiesText);

            return new GeneratedFile
            {
                FileName = $"{entityName}.cs",
                Content = code,
                Database = database
            };
        }

        private static string GenerateProperty(ColumnSchema column)
        {
            var attributes = new List<string>();

            if (!column.IsNullable)
            {
                attributes.Add("[Required]");
            }

            if (IsStringType(column.DataType) &&
                column.CharacterMaximumLength.HasValue &&
                column.CharacterMaximumLength.Value > 0)
            {
                attributes.Add($"[StringLength({column.CharacterMaximumLength.Value})]");
            }

            var result = new StringBuilder();

            foreach (var attribute in attributes)
            {
                result.Append("\t");
                result.AppendLine(attribute);
            }

            var (csharpType, valueType) = CSharpTypeConverter.GetCSharpType(column.DataType, column.UserDefinedType, column.IsNullable);
            var defaultValue = CSharpTypeConverter.GetDefaultValue(valueType, column.IsNullable);
            result.Append("\t");
            result.Append($"public {csharpType} {column.ColumnName} {{ get; set; }} = {defaultValue};");
            result.AppendLine();

            return result.ToString();
        }

        private static bool IsStringType(string dataType)
        {
            return dataType.ToLower() switch
            {
                "char" or "varchar" or "text" or "nchar" or "nvarchar" or "ntext" => true,
                _ when dataType.StartsWith("varchar", StringComparison.OrdinalIgnoreCase) => true,
                _ when dataType.StartsWith("nvarchar", StringComparison.OrdinalIgnoreCase) => true,
                _ => false
            };
        }
    }
}
