using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Generator.Database.Generators
{
    /// <summary>wwwroot/i18n/{Domain}.{baseCulture}.json → 타입드 접근자(AppText.g.cs) 생성.
    /// 키에 {0}·{1} 플레이스홀더가 있으면 인자 메서드, 없으면 프로퍼티. 생성물은 커밋(수동 실행).</summary>
    public sealed class LocalizationGenerator
    {
        private static readonly Regex PlaceholderPattern = new(@"\{(\d+)\}", RegexOptions.Compiled);
        private static readonly Regex NonAlphaNumeric = new(@"[^A-Za-z0-9]+", RegexOptions.Compiled);

        public string Generate(string resourcesPath, string baseCulture, string ns)
        {
            string suffix = $".{baseCulture}.json";
            var files = Directory.GetFiles(resourcesPath, $"*{suffix}").OrderBy(f => f, StringComparer.Ordinal).ToList();

            var domains = new List<(string Domain, List<KeyValuePair<string, string>> Entries)>();
            foreach (string file in files)
            {
                string fileName = Path.GetFileName(file);
                string domain = fileName.Substring(0, fileName.Length - suffix.Length);
                Dictionary<string, string> dict =
                    JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(file)) ?? new();
                domains.Add((domain, dict.ToList()));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"// wwwroot/i18n/*{suffix} 기준 생성 — 수동 편집 금지. Generator.Database 재실행으로 갱신.");
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class AppText");
            sb.AppendLine("    {");
            sb.AppendLine($"        internal static readonly string[] Domains = {{ {string.Join(", ", domains.Select(d => $"\"{d.Domain}\""))} }};");

            foreach ((string domain, List<KeyValuePair<string, string>> entries) in domains)
            {
                sb.AppendLine();
                sb.AppendLine($"        public static class {domain}");
                sb.AppendLine("        {");
                foreach ((string key, string value) in entries)
                {
                    string member = ToPascalCase(key);
                    string fullKey = $"{domain}.{key}";
                    int arity = PlaceholderArity(value);
                    if (arity == 0)
                    {
                        sb.AppendLine($"            /// <summary>{Escape(value)}</summary>");
                        sb.AppendLine($"            public static string {member} => Loc.Get(\"{fullKey}\");");
                    }
                    else
                    {
                        string pars = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"object arg{i}"));
                        string argsArray = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"arg{i}"));
                        sb.AppendLine($"            /// <summary>{Escape(value)}</summary>");
                        sb.AppendLine($"            public static string {member}({pars}) => Loc.Format(\"{fullKey}\", {argsArray});");
                    }
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static int PlaceholderArity(string value)
        {
            int max = -1;
            foreach (Match match in PlaceholderPattern.Matches(value))
            {
                max = Math.Max(max, int.Parse(match.Groups[1].Value));
            }

            return max + 1;
        }

        private static string ToPascalCase(string key)
        {
            IEnumerable<string> parts = NonAlphaNumeric.Split(key).Where(p => p.Length > 0);
            var sb = new StringBuilder();
            foreach (string part in parts)
            {
                sb.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    sb.Append(part.Substring(1));
                }
            }

            return sb.Length == 0 ? "_" : sb.ToString();
        }

        private static string Escape(string value)
        {
            return value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
    }
}
