using Generator.Database.Analyzers;
using Generator.Database.Models;
using System.Text;

namespace Generator.Database.Generators
{
    public class ProcedureGenerator(string rootNamespace = "")
    {
        private readonly string RootNamespace = rootNamespace;

        private const string CstProcedureTemplate = @"// <auto-generated />
// This file was automatically generated from SQL procedure definition. Do not edit manually.

#nullable enable

using Dapper;
using PlayGround.Infrastructure.Database;
using PlayGround.Infrastructure.Database.Base;

namespace {NAMESPACE};

/// <summary>
/// {DESCRIPTION}
/// </summary>
public class {CLASS_NAME}(RepositoryBase repository) : ProcedureBase(repository)
{
    public override string Procedure => ""[{SCHEMA}].[{PROCEDURE_NAME}]"";

{PROPERTIES}
    public override DynamicParameters BuildParameters()
    {
{BUILD_PARAMETERS}
        return Parameters;
    }

    public override bool HasReturnValue() => true;

    public override int GetReturnValue() => Parameters.Get<int>(""@ReturnValue"");
}";

        public List<GeneratedFile> GenerateProcedures(string database, List<ProcedureSchema> procedures)
        {
            var generatedFiles = new List<GeneratedFile>();

            foreach (var proc in procedures)
            {
                var generatedFile = GenerateProcedure(database, proc);
                if (generatedFile != null)
                {
                    generatedFiles.Add(generatedFile);
                }
            }

            return generatedFiles;
        }

        private GeneratedFile? GenerateProcedure(string database, ProcedureSchema proc)
        {
            var description = proc.ProcedureName;

            var propertiesBuilder = new StringBuilder();
            var buildParamsBuilder = new StringBuilder();

            foreach (var param in proc.Parameters)
            {
                var (csharpType, valueType) = CSharpTypeConverter.GetCSharpType(param.DataType, null, param.IsNullable);
                var defaultValue = GetParameterDefaultValue(param, valueType);

                propertiesBuilder.Append("\t");
                propertiesBuilder.AppendLine($"public {csharpType} {param.ParameterName} {{ get; set; }} = {defaultValue};");
            }

            if (proc.Parameters.Count > 0)
            {
                propertiesBuilder.AppendLine();
            }

            foreach (var param in proc.Parameters)
            {
                buildParamsBuilder.Append("\t\t");
                buildParamsBuilder.AppendLine($"Parameters.Add(\"@{param.ParameterName}\", {param.ParameterName});");
            }

            buildParamsBuilder.Append("\t\t");
            buildParamsBuilder.AppendLine("Parameters.Add(\"@ReturnValue\", dbType: System.Data.DbType.Int32, direction: System.Data.ParameterDirection.ReturnValue);");

            var code = CstProcedureTemplate
                .Replace("{NAMESPACE}", NamespaceBuilder.Build(RootNamespace, database, "Procedures"))
                .Replace("{DESCRIPTION}", description)
                .Replace("{SCHEMA}", proc.Schema)
                .Replace("{PROCEDURE_NAME}", proc.ProcedureName)
                .Replace("{CLASS_NAME}", proc.ProcedureName)
                .Replace("{PROPERTIES}", propertiesBuilder.ToString().TrimEnd())
                .Replace("{BUILD_PARAMETERS}", buildParamsBuilder.ToString().TrimEnd());

            return new GeneratedFile
            {
                FileName = $"{proc.ProcedureName}.cs",
                Content = code,
                Database = database
            };
        }

        private static string GetParameterDefaultValue(ParameterSchema param, CSharpTypeConverter.ValueType valueType)
        {
            if (param.IsNullable)
            {
                return "null";
            }

            if (param.HasDefault && !string.IsNullOrEmpty(param.DefaultValue))
            {
                var raw = param.DefaultValue.Trim();

                if (raw.StartsWith("'") && raw.EndsWith("'"))
                {
                    var strValue = raw.Trim('\'');
                    return $"\"{strValue}\"";
                }

                if (int.TryParse(raw, out _) || double.TryParse(raw, out _))
                {
                    return raw;
                }
            }

            return CSharpTypeConverter.GetDefaultValue(valueType, param.IsNullable);
        }
    }
}
