using Generator.Database.Analyzers;
using Generator.Database.Models;
using System.Text;

namespace Generator.Database.Generators
{
    public class QueryGenerator(string rootNamespace = "")
    {
        private readonly string RootNamespace = rootNamespace;

        private const string CstQueryTemplate = @"// <auto-generated />
// This file was automatically generated from SQL query definition. Do not edit manually.

#nullable enable

using PlayGround.Infrastructure.Database;
using PlayGround.Infrastructure.Database.Base;

namespace {NAMESPACE};

/// <summary>
/// {DESCRIPTION}
/// </summary>
public class {CLASS_NAME}(RepositoryBase repository) : QueryBase(repository)
{
    public override string Sql => @""{SQL}"";
{PROPERTIES}
}";

        private const string CstQueryWithParamsTemplate = @"// <auto-generated />
// This file was automatically generated from SQL query definition. Do not edit manually.

#nullable enable

using PlayGround.Infrastructure.Database;
using PlayGround.Infrastructure.Database.Base;

namespace {NAMESPACE};

/// <summary>
/// {DESCRIPTION}
/// </summary>
public class {CLASS_NAME}(RepositoryBase repository) : QueryBase(repository)
{
    public override string Sql => @""{SQL}"";

{PROPERTIES}
    public override object BuildParameters() => new { {BUILD_PARAMETERS} };
}";

        public List<GeneratedFile> GenerateQueries(string database, List<QuerySchema> queries)
        {
            var generatedFiles = new List<GeneratedFile>();

            foreach (var query in queries)
            {
                var generatedFile = GenerateQuery(database, query);
                if (generatedFile != null)
                {
                    generatedFiles.Add(generatedFile);
                }
            }

            return generatedFiles;
        }

        private static string IndentSqlLines(string sql)
        {
            var lines = sql.Replace("\r\n", "\n").Replace("\r", "\n").Split('\n');
            if (lines.Length <= 1)
            {
                return sql;
            }

            return lines[0] + "\n" + string.Join("\n", lines.Skip(1).Select(l => "\t" + l));
        }

        private GeneratedFile? GenerateQuery(string database, QuerySchema query)
        {
            var sqlEscaped = IndentSqlLines(query.SqlBody).Replace("\"", "\"\"");

            if (query.Parameters.Count == 0)
            {
                var code = CstQueryTemplate
                    .Replace("{NAMESPACE}", NamespaceBuilder.Build(RootNamespace, database, "Queries"))
                    .Replace("{DESCRIPTION}", query.QueryName)
                    .Replace("{CLASS_NAME}", query.QueryName)
                    .Replace("{SQL}", sqlEscaped)
                    .Replace("{PROPERTIES}", string.Empty);

                return new GeneratedFile
                {
                    FileName = $"{query.QueryName}.cs",
                    Content = code,
                    Database = database
                };
            }
            else
            {
                var propertiesBuilder = new StringBuilder();
                var buildParamNames = new List<string>();

                foreach (var param in query.Parameters)
                {
                    var (csharpType, valueType) = CSharpTypeConverter.GetCSharpType(param.DataType, null, param.IsNullable);
                    var defaultValue = param.IsNullable ? "null" : CSharpTypeConverter.GetDefaultValue(valueType, false);

                    propertiesBuilder.Append("\t");
                    propertiesBuilder.AppendLine($"public {csharpType} {param.ParameterName} {{ get; set; }} = {defaultValue};");

                    buildParamNames.Add(param.ParameterName);
                }

                var code = CstQueryWithParamsTemplate
                    .Replace("{NAMESPACE}", NamespaceBuilder.Build(RootNamespace, database, "Queries"))
                    .Replace("{DESCRIPTION}", query.QueryName)
                    .Replace("{CLASS_NAME}", query.QueryName)
                    .Replace("{SQL}", sqlEscaped)
                    .Replace("{PROPERTIES}", propertiesBuilder.ToString().TrimEnd())
                    .Replace("{BUILD_PARAMETERS}", string.Join(", ", buildParamNames));

                return new GeneratedFile
                {
                    FileName = $"{query.QueryName}.cs",
                    Content = code,
                    Database = database
                };
            }
        }
    }
}
