using Generator.Database.Analyzers;
using Generator.Database.Models;
using System.Text;

namespace Generator.Database.Generators
{
    public class TableEntityGenerator(string rootNamespace = "")
    {
        private readonly string RootNamespace = rootNamespace;

        private const string CstEntityTemplate = @"// <auto-generated />
// This file was automatically generated. Do not edit manually.

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace {NAMESPACE};

/// <summary>
/// {DESCRIPTION}
/// </summary>
[Table(""{TABLE_NAME}"", Schema = ""{SCHEMA}"")]
public class {CLASS_NAME}
{
{PROPERTIES}
}";

        public List<GeneratedFile> GenerateEntities(string database, List<TableSchema> tables)
        {
            var generatedFiles = new List<GeneratedFile>();

            foreach (var table in tables)
            {
                var className = $"{table.TableName}Entity";
                var generatedFile = GenerateEntity(database, table, className);
                generatedFiles.Add(generatedFile);
            }

            return generatedFiles;
        }

        private GeneratedFile GenerateEntity(string database, TableSchema table, string className)
        {
            var builder = new StringBuilder();
            foreach (var column in table.Columns)
            {
                var property = GeneratePropertyValue(column);
                builder.AppendLine(property);
            }

            var code = CstEntityTemplate
                .Replace("{NAMESPACE}", NamespaceBuilder.Build(RootNamespace, database, "Entities"))
                .Replace("{DESCRIPTION}", table.TableName)
                .Replace("{TABLE_NAME}", table.TableName)
                .Replace("{SCHEMA}", table.Schema)
                .Replace("{CLASS_NAME}", className)
                .Replace("{PROPERTIES}", builder.ToString().TrimEnd());

            return new GeneratedFile
            {
                FileName = $"{className}.cs",
                Content = code,
                Database = database
            };
        }

        private static string GeneratePropertyValue(ColumnSchema column)
        {
            var attributes = new List<string>();

            if (!column.IsNullable)
            {
                attributes.Add("[Required]");
            }

            if (IsStringType(column.DataType) &&
                column.CharacterMaximumLength.HasValue &&
                column.CharacterMaximumLength.Value > 0)
            {
                attributes.Add($"[StringLength({column.CharacterMaximumLength.Value})]");
            }

            var result = new StringBuilder();

            foreach (var attribute in attributes)
            {
                result.Append("\t");
                result.AppendLine(attribute);
            }

            var (csharpType, valueType) = CSharpTypeConverter.GetCSharpType(column.DataType, column.UserDefinedType, column.IsNullable);
            var defaultValue = CSharpTypeConverter.GetDefaultValue(valueType, column.IsNullable);
            result.Append("\t");
            result.Append($"public {csharpType} {column.ColumnName} {{ get; set; }} = {defaultValue};");
            result.AppendLine();

            return result.ToString();
        }

        private static bool IsStringType(string dataType)
        {
            return dataType.ToLower() switch
            {
                "char" or "varchar" or "text" or "nchar" or "nvarchar" or "ntext" => true,
                _ when dataType.StartsWith("varchar", StringComparison.OrdinalIgnoreCase) => true,
                _ when dataType.StartsWith("nvarchar", StringComparison.OrdinalIgnoreCase) => true,
                _ => false
            };
        }
    }
}
